# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        container_name: laravel-sail
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                TZ: 'America/Sao_Paulo'
                WWWGROUP: '${WWWGROUP}'
                SSH_PASS: '${SSH_PASS:-secret}'
        image: sail-8.2/app-ssh-ws
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '9000:9000'
            - '${SSH_PORT:-22}:22'
            - '${LARAVEL_WEBSOCKETS_PORT:-6001}:6001'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - './docker/8.2/extras/php-cli.ini:/etc/php/8.2/cli/conf.d/99-sail.ini'
            - './docker/8.2/extras/php-fpm.ini:/etc/php/8.2/fpm/conf.d/99-sail.ini'
            - './docker/8.2/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - sail

    web:
      image: nginx:latest
      container_name: webserver
      restart: unless-stopped
      volumes:
        - ./docker/nginx/templates:/etc/nginx/templates
        - ./docker/nginx/certs:/etc/nginx/certs
        - .:/var/www/html
      ports:
        - '${APP_SSL_PORT:-443}:443'
        - '${APP_PORT:-80}:80'
      networks:
        - sail
      #                 ipv4_address: ${APP_ADDRESS}
      depends_on:
        - laravel.test

networks:
    sail:
        driver: bridge
